### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by insurgent92** [DeepBaksuVision/Modu_ObjectDetection#18]
Already pushed 문서에 대해서 어떻게 이슈를 열어야 할지 몰라서 우선은 이렇게..

https://github.com/DeepBaksuVision/Modu_ObjectDetection/commit/b818cfe15c359ab68c99a43f9d540374ec4459d6#r31428328

**Comment by ssaru** [comment]
해당 issue를 reopen하시고, 현재 프로젝트로 끌고와도 되지 않을까요?

**Comment by ssaru** [comment]
@insurgent92 해당 내용에 대해서 상세한 디스크립션 부탁드릴게요
