### ISSUE TITLE
[YOLOv1] data_collate function

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/Modu_ObjectDetection#2]

**Comment by insurgent92** [comment]
#20 에 있는 @ssaru 님의 comment에 관한 feedback을 위해서 #2를 다시 열었습니다.
# Table of Feedbacks 
1. https://github.com/DeepBaksuVision/Modu_ObjectDetection/pull/20#discussion_r236262130
2. https://github.com/DeepBaksuVision/Modu_ObjectDetection/pull/20#discussion_r236262700
